
-- 1.What is the revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue
from customer
group by gender;

-- 2.Which customers used a discount but still spent more that the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >=(select avg(purchase_amount) from customer_shopping_behaviour);

-- 3.Which are the top 5 products with highest average review rating

select item_purchased as product,round(avg(review_rating),2) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;

-- 4.Compare the average purchase amount between Standard and express shipping
select shipping_type,avg(purchase_amount) as avg_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- 5.Do subscribed customers spend more ? compare avg spend and total revenue between subscribers and non-subscribers
select subscription_status,count(customer_id) as total_customers,round(avg(purchase_amount),2) as avg_spend ,round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by avg_spend,total_revenue desc;

-- 6.Which 5 products have the highest percentage of purchases with discount_applied

SELECT item_purchased,
       ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
             / COUNT(*) * 100, 2) AS discount_percentage
FROM customer
GROUP BY item_purchased
order by discount_percentage desc
limit 5;

-- 6.Segment customers into new,retuening and loyal baesd on thier total no of previous purchases,and show the count of each segment

with customer_type as(
  select customer_id,previous_purchases,
  case when previous_purchases= 1 then "New"
       when previous_purchases between 2 and 10 then "Returning"
	   else 'Loyal'
       end as customer_segment
   from customer    
)

select customer_segment,count(*) as 'Number of customers'
from customer_type
group by customer_segment;

-- 8.what are the top 3 most purchased products in each category based on purchase_amount?

select category,item_purchased,total
from(
    select category,item_purchased,sum(purchase_amount) as total,
    dense_rank() over(partition by category order by sum(purchase_amount) desc) as rnk
    from customer
    group by category, item_purchased
)t
where t.rnk<=3;

-- 9.Are customers who are repeat buyers (more than 5 previous buys) also likely to subscribe?

select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status; 

-- 10.what is the revenue contribution by age_group

select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group;

